name: checklatest
on:
  workflow_dispatch:
  schedule:
    - cron: "15 4,5 * * *"   # <=== Change this value
permissions:
  actions: write
env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  checklatest-protoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - id: check
        run: npx checklatest protoc >> "$GITHUB_OUTPUT"
      - if: ${{ steps.check.outputs.latest }}
        run: gh workflow run update-protoc.yaml -f version=${{steps.check.outputs.latest}}
  checklatest-conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - id: check
        run: npx checklatest conformance >> "$GITHUB_OUTPUT"
      - if: ${{ steps.check.outputs.latest }}
        run: gh workflow run update-conformance.yaml -f version=${{steps.check.outputs.latest}}
