name: ci
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all

env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run all
          npx diffcheck
      - run: |
          npx update-protoc current
          npx update-conformance current
          npx diffcheck
