name: update-protoc
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream version, e.g. v29.2'
        required: true
        type: string
permissions: read-all
env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  update-protoc:
    runs-on: ubuntu-latest
    if: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx update-protoc ${{ inputs.version }}
      # TODO open PR
      - run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - run: npx diffcheck
