name: update-conformance
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream version, e.g. v29.2'
        required: true
        type: string
permissions:
  # https://github.com/peter-evans/create-pull-request/tree/main?tab=readme-ov-file#token
  contents: write
  pull-requests: write
env:
  # https://consoledonottrack.com/
  DO_NOT_TRACK: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}
jobs:
  build-conformance-linux-x64:
    runs-on: ubuntu-latest
    if: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - run: npm ci
      - run: npx update-conformance ${{ inputs.version }}
      - run: npx build-conformance
      - uses: actions/upload-artifact@v4
        with:
          name: conformance_test_runner-linux-x64
          path: packages/protobuf-conformance/.tmp/bazel-bin/conformance/conformance_test_runner
  build-conformance-darwin-x64:
    runs-on: macos-13
    if: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - run: npm ci
      - run: npx update-conformance ${{ inputs.version }}
      - run: npx build-conformance
      - uses: actions/upload-artifact@v4
        with:
          name: conformance_test_runner-darwin-x64
          path: packages/protobuf-conformance/.tmp/bazel-bin/conformance/conformance_test_runner
  pr:
    runs-on: ubuntu-latest
    needs: [build-conformance-darwin-x64, build-conformance-linux-x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: conformance_test_runner-darwin-x64
          path: packages/protobuf-conformance/conformance_test_runner-darwin-x64
      - uses: actions/download-artifact@v4
        with:
          name: conformance_test_runner-linux-x64
          path: packages/protobuf-conformance/conformance_test_runner-linux-x64
      - run: |
          chmod +x packages/protobuf-conformance/conformance_test_runner-darwin-x64
          chmod +x packages/protobuf-conformance/conformance_test_runner-linux-x64
      - id: checkversion
        run: |
          npm ci
          npx update-conformance ${{inputs.version}}
          npx checkversion conformance >> "$GITHUB_OUTPUT"
      - uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: update-conformance-${{ steps.checkversion.outputs.package_version }}
          delete-branch: true
          commit-message: Update protobuf-conformance to ${{ inputs.version }}
          title: Update protobuf-conformance to ${{ inputs.version }}
          body: |
            Update the package `protobuf-conformance` to the upstream release [${{ inputs.version }}](https://github.com/protocolbuffers/protobuf/releases/tag/${{ inputs.version }}).
            Merging this PR will publish version ${{ steps.checkversion.outputs.package_version }} of this package.
