name: update-protoc
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream version, e.g. v29.2'
        required: true
        type: string
permissions:
  # https://github.com/peter-evans/create-pull-request/tree/main?tab=readme-ov-file#token
  contents: write
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - id: localversion
        run: |
          npm ci
          npx update-protoc ${{inputs.version}}
          npx version local protoc >> "$GITHUB_OUTPUT"
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PROTOBUF_NPM_GITHUB_TOKEN }}
          base: main
          branch: update-protoc-${{ steps.localversion.outputs.package_version }}
          delete-branch: true
          commit-message: Update protoc to ${{ inputs.version }}
          title: Update protoc to ${{ inputs.version }}
          body: |
            Update the package `protoc` to the upstream release [${{ inputs.version }}](https://github.com/protocolbuffers/protobuf/releases/tag/${{ inputs.version }}).
            Merging this PR will tag a release, and publish version ${{ steps.localversion.outputs.package_version }} of the package.
